### ISSUE TITLE
service crash - panic: malformed-request

### ISSUE THREAD

**Issue by harvald** [opthomas-prime/xmpp-webhook#21]
service xmpp-webhook crash on start with log message:
`panic: malformed-request

goroutine 1 [running]:
main.panicOnErr(...)
        /root/xmpp-webhook/xmpp-webhook-master/main.go:24
main.main()
        /root/xmpp-webhook/xmpp-webhook-master/main.go:100 +0x80e`

**Comment by tmsmr** [comment]
Hey @harvald, seems like the XMPP-client is not able to connect to your server. Can you provide some details about the environment?

**Comment by harvald** [comment]
OS: Ubuntu 20.04
XMPP: Prosody 0.11.4 on the same host
From Prosody logs:
`Jun 17 14:09:11 c2s560d2d807f40 debug   Client sent opening <stream:stream> to harvald.pl.eu.org
Jun 17 14:09:11 c2s560d2d807f40 debug   Sending[c2s_unauthed]: <?xml version='1.0'?>
Jun 17 14:09:11 c2s560d2d807f40 debug   Sending[c2s_unauthed]: <stream:stream xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' version='1.0
' id='8ac66e23-e03b-4440-8b50-9b5a77c0cfa2' xml:lang='en' from='harvald.pl.eu.org'>
Jun 17 14:09:11 c2s560d2d807f40 debug   Sent reply <stream:stream> to client
Jun 17 14:09:11 c2s560d2d807f40 info    Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
Jun 17 14:09:11 c2s560d2d807f40 debug   Not offering disabled mechanism DIGEST-MD5
Jun 17 14:09:11 c2s560d2d807f40 debug   Offering mechanism SCRAM-SHA-1
Jun 17 14:09:11 c2s560d2d807f40 debug   Offering mechanism SCRAM-SHA-1-PLUS
Jun 17 14:09:11 c2s560d2d807f40 debug   Offering mechanism PLAIN
Jun 17 14:09:11 c2s560d2d807f40 debug   Sending[c2s_unauthed]: <stream:features>
Jun 17 14:09:11 c2s560d2d807f40 debug   Received[c2s_unauthed]: <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='SCRAM-SHA-1-PLUS'>
Jun 17 14:09:11 harvald.pl.eu.org:auth_internal_plain   debug   get_password for username 'harvald'
Jun 17 14:09:11 harvald.pl.eu.org:saslauth      debug   sasl reply: <challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cj1FQ0NrRUFVRE9ZMksyMVJSZlA5RlRnYTc2NDZj
M2QtMGUxYS00ODIxLTg1ZmQtODdhZGYzZTg0YzgzLHM9T1dRellqVXhPRFl0WXpGbFpTMDBNamRtTFRoa1pERXRPR00zTXpRM056SmxZalV5LGk9NDA5Ng==</challenge>
Jun 17 14:09:11 c2s560d2d807f40 debug   Sending[c2s_unauthed]: <challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Jun 17 14:09:11 c2s560d2d807f40 debug   Received[c2s_unauthed]: <response xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Jun 17 14:09:11 harvald.pl.eu.org:saslauth      debug   sasl reply: <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><malformed-request/><text>Invalid channel
binding value.</text></failure>
Jun 17 14:09:11 c2s560d2d807f40 debug   Sending[c2s_unauthed]: <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Jun 17 14:09:11 socket  debug   server.lua: client 193.164.135.101:44744 read error: closed
Jun 17 14:09:11 c2s560d2d807f40 info    Client disconnected: closed
Jun 17 14:09:11 c2s560d2d807f40 debug   Destroying session for (unknown) ((unknown)@harvald.pl.eu.org): closed
Jun 17 14:09:11 socket  debug   server.lua: closed client handler and removed socket from list

`

**Comment by tmsmr** [comment]
Can you provide the (anonymized) webhook configuration?

**Comment by harvald** [comment]
XMPP_ID='server@harvald.pl.eu.org'
XMPP_PASS='xxxxxxxx'
XMPP_RECIPIENTS='harvald@harvald.pl.eu.org'

also tried with 
XMPP_SKIP_VERIFY
XMPP_OVER_TLS
